name: pin_pon
description: Juego de pin pong desarrollado en Dart como práctica de programación.
version: 1.0.0
# repository: https://github.com/ronmysalimeyitsu-debug/daseraollo_dart.git

environment:
  sdk: ^3.13.0

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
